version: '2'
services:
  redis:
    image: redis
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  web:
    restart: always
    build: .
    depends_on:
      - redis
    volumes:
      - ./scripts:/usr/src/scripts
      - ./index.html:/usr/src/app/index.html
      - ./confirm.html:/usr/src/app/confirm.html
    links:
      - redis:redis
    ports:
      - "8080:8080"
  nginxproxy:
    restart: always
    build: ./nginxproxy/
    ports:
      - "80:80"
    volumes:
      - /www/static
      - /www/media
    volumes_from:
      - web
    links:
      - web
    depends_on:
      - web