version: '2'
services:
  redis:
    image: redis
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  postgresql:
    build: ./postgresql/.
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    restart: always
    build: .
    depends_on:
      - redis
    volumes:
      # - ./services:/usr/src/app/services
      # - ./stylesheets:/usr/src/app/stylesheets
      # - ./server:/usr/src/app/server/
      - ./scripts:/usr/src/scripts
      - ./index.html:/usr/src/app/index.html
    links:
      - postgresql:postgresql
    ports:
      - "8080:8080"
    env_file: .env
  nginxproxy:
    restart: always
    build: ./nginxproxy/
    ports:
      - "80:80"
    volumes:
      - /www/static
      - /www/media
    volumes_from:
      - web
    links:
      - web
    depends_on:
      - web