// Generated by CoffeeScript 1.10.0
(function() {
  var path;
  'use strict';
  var app, async, client, express, http, path, redis, redisHOST, request, serveStatic;

  express = require('express');

  request = require('request');

  path = require('path');

  http = require('http');

  path = require('path');

  async = require('async');

  redis = require('redis');

  serveStatic = require('serve-static');

  redisHOST = 'redis';

  client = redis.createClient('6379', redisHOST);

  client.on('error', function(err) {
    console.log('Error in connecting to redis database' + err);
  });

  app = express();

  app.disable('etag');

  app.set('trust proxy', true);

  app.use(serveStatic('./bower_components/semantic/dist'));

  app.use(serveStatic('./bower_components/jquery/dist'));

  app.use(serveStatic('./scripts'));

  app.use(serveStatic('./stylesheets'));

  app.use(serveStatic('./scripts'));

  app.use(serveStatic('./', {
    'index': ['index.html', 'index.htm']
  }));

  app.set('view engine', 'ejs');

  app.get('/', function(req, res) {
    res.render('index', function(err, html) {
      res.send(html);
    });
  });

  app.get('/forminputemail/:email', function(req, res) {
    console.log(req.params.email);
    client.sadd(['emails', req.params.email], function(err, reply) {
      return res.json({
        'status': reply
      });
    });
  });

  module.exports = {
    app: app,
    port: 8080
  };

}).call(this);
