// Generated by CoffeeScript 1.10.0
(function() {
  var validationRules;

  validationRules = {
    fields: {
      first_name: {
        identifier: 'first_name',
        rules: [
          {
            type: 'empty',
            prompt: 'Please enter your first name'
          }
        ]
      },
      last_name: {
        identifier: 'last_name',
        rules: [
          {
            type: 'empty',
            prompt: 'Please enter your last name'
          }
        ]
      },
      project_name: {
        identifier: 'project_name',
        rules: [
          {
            type: 'empty',
            prompt: 'Please enter a project name'
          }
        ]
      },
      organization_name: {
        identifier: 'organization_name',
        rules: [
          {
            type: 'empty',
            prompt: 'Please enter a  name'
          }
        ]
      },
      email: {
        identifier: 'email',
        rules: [
          {
            type: 'empty',
            prompt: 'Please enter a email'
          }
        ]
      },
      password: {
        identifier: 'password',
        rules: [
          {
            type: 'empty',
            prompt: 'Please enter a password'
          }, {
            type: 'minLength[6]',
            prompt: 'Your password must be at least {ruleValue} characters'
          }
        ]
      }
    }
  };

  $('.ui.form').form(validationRules, {
    inline: true,
    on: 'blur',
    transition: 'fade down'
  });

  $('.ui.form').submit(function(e) {
    return false;
  });

  $('.ui.form .submit.button').api({
    method: 'GET',
    serializeForm: true,
    data: $('.ui.form').form('get values'),
    beforeSend: (function(_this) {
      return function(settings) {
        var $form, email;
        $form = $('.ui.form');
        email = $form.form('get value', 'email');
        if ($(".ui.form").form('is valid')[1] === true) {
          settings.url = "/forminputemail/" + email;
          return settings;
        } else {
          settings.url = "/";
          return settings;
        }
      };
    })(this),
    onSuccess: function(data) {
      var valid;
      valid = $(".ui.form").form('is valid');
      $('.ui.form').submit(function(e) {
        return true;
      });
      if (data.status === 0 && valid[1] === true) {
        return $('#signinprompt').modal('setting', 'transition', 'fade').modal('show');
      } else {
        return $('#confirmationpage').modal('setting', 'transition', 'fade').modal('show');
      }
    }
  });

}).call(this);
